const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Button.Acts.SetSize,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.uppercase
	];
};
self.C3_JsPropNameTable = [
	{kategori: 0},
	{btnSinir: 0},
	{btnEndokrin: 0},
	{btnDuyu: 0},
	{btnDestekHar: 0},
	{btnSindirim: 0},
	{btnDolasim: 0},
	{btnSolunum: 0},
	{btnUriner: 0},
	{btnUreme: 0},
	{liderlikTablosu: 0},
	{misafir: 0},
	{Tween: 0},
	{isimleGir: 0},
	{arrYanlisTus: 0},
	{joker50: 0},
	{jokerSeyirci: 0},
	{yuzdeA: 0},
	{yuzdeB: 0},
	{yuzdeC: 0},
	{yuzdeD: 0},
	{jokerTelefontxt: 0},
	{jokerTelefon: 0},
	{jokerGec: 0},
	{btnA: 0},
	{btnB: 0},
	{btnC: 0},
	{btnD: 0},
	{arkaplanOyun: 0},
	{txtPuan: 0},
	{Pin: 0},
	{txtSoru: 0},
	{usedIndexes: 0},
	{Geri: 0},
	{soruMetni: 0},
	{tusA: 0},
	{tusB: 0},
	{tusC: 0},
	{tusD: 0},
	{tusAmetin: 0},
	{tusBmetin: 0},
	{tusCmetin: 0},
	{tusDmetin: 0},
	{soruMetni2: 0},
	{txtSure: 0},
	{txtSayisiSoru: 0},
	{tusAnaMenu: 0},
	{tusEnyuksekskor: 0},
	{mtn1: 0},
	{istatistik: 0},
	{anamenutxt: 0},
	{skorlartxt: 0},
	{arkaplan: 0},
	{liderlik: 0},
	{ses: 0},
	{mute: 0},
	{Oyna: 0},
	{liderlik2txt: 0},
	{oynatxt: 0},
	{AJAX: 0},
	{JSON: 0},
	{Audio: 0},
	{Mouse: 0},
	{versiyon: 0},
	{TextInput: 0},
	{gonder: 0},
	{Tablo: 0},
	{Liste: 0},
	{Touch: 0},
	{Browser: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{ekranOrani: 0},
	{nick: 0},
	{raw: 0},
	{line: 0},
	{isim: 0},
	{skor: 0},
	{puan: 0},
	{soruIndex: 0},
	{dogruCevap: 0},
	{tempIndex: 0},
	{sorubul: 0},
	{seciliKategori: 0},
	{oncekiAd: 0},
	{oncekiSkor: 0},
	{kalanSoru: 0},
	{sure: 0},
	{soruCevaplandiMi: 0},
	{dogruSayisi: 0},
	{yanlisSayisi: 0},
	{joker50Kullanildi: 0},
	{silIndex11: 0},
	{silIndex12: 0},
	{sec11: 0},
	{sec12: 0},
	{jokerSeyirciKullanildi: 0},
	{dogruYuzde: 0},
	{yanlisYuzde: 0},
	{jokerTelefonKullanildi: 0},
	{secilen2: 0},
	{tahminTut: 0},
	{jokerGecKullanildi: 0},
	{y1: 0},
	{y2: 0},
	{y3: 0}
];

self.InstanceType = {
	kategori: class extends self.ITextInstance {},
	btnSinir: class extends self.IButtonInstance {},
	btnEndokrin: class extends self.IButtonInstance {},
	btnDuyu: class extends self.IButtonInstance {},
	btnDestekHar: class extends self.IButtonInstance {},
	btnSindirim: class extends self.IButtonInstance {},
	btnDolasim: class extends self.IButtonInstance {},
	btnSolunum: class extends self.IButtonInstance {},
	btnUriner: class extends self.IButtonInstance {},
	btnUreme: class extends self.IButtonInstance {},
	liderlikTablosu: class extends self.ITextInstance {},
	misafir: class extends self.ITextInstance {},
	isimleGir: class extends self.ITextInstance {},
	arrYanlisTus: class extends self.IArrayInstance {},
	joker50: class extends self.IButtonInstance {},
	jokerSeyirci: class extends self.IButtonInstance {},
	yuzdeA: class extends self.ITextInstance {},
	yuzdeB: class extends self.ITextInstance {},
	yuzdeC: class extends self.ITextInstance {},
	yuzdeD: class extends self.ITextInstance {},
	jokerTelefontxt: class extends self.ITextInstance {},
	jokerTelefon: class extends self.IButtonInstance {},
	jokerGec: class extends self.IButtonInstance {},
	btnA: class extends self.IButtonInstance {},
	btnB: class extends self.IButtonInstance {},
	btnC: class extends self.IButtonInstance {},
	btnD: class extends self.IButtonInstance {},
	arkaplanOyun: class extends self.ISpriteInstance {},
	txtPuan: class extends self.ITextInstance {},
	txtSoru: class extends self.ITextInstance {},
	usedIndexes: class extends self.IArrayInstance {},
	Geri: class extends self.IButtonInstance {},
	soruMetni: class extends self.ISpriteInstance {},
	tusA: class extends self.ISpriteInstance {},
	tusB: class extends self.ISpriteInstance {},
	tusC: class extends self.ISpriteInstance {},
	tusD: class extends self.ISpriteInstance {},
	tusAmetin: class extends self.ITextInstance {},
	tusBmetin: class extends self.ITextInstance {},
	tusCmetin: class extends self.ITextInstance {},
	tusDmetin: class extends self.ITextInstance {},
	soruMetni2: class extends self.IWorldInstance {},
	txtSure: class extends self.ITextInstance {},
	txtSayisiSoru: class extends self.ITextInstance {},
	tusAnaMenu: class extends self.IWorldInstance {},
	tusEnyuksekskor: class extends self.IWorldInstance {},
	mtn1: class extends self.ITextInstance {},
	istatistik: class extends self.ITextInstance {},
	anamenutxt: class extends self.ITextInstance {},
	skorlartxt: class extends self.ITextInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	liderlik: class extends self.ISpriteInstance {},
	mute: class extends self.ISpriteInstance {},
	Oyna: class extends self.ISpriteInstance {},
	liderlik2txt: class extends self.ITextInstance {},
	oynatxt: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	versiyon: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	gonder: class extends self.IButtonInstance {},
	Tablo: class extends self.IButtonInstance {},
	Liste: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {}
}