const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Text.Acts.AppendText
	];
};
self.C3_JsPropNameTable = [
	{arkaplan: 0},
	{Oyna: 0},
	{liderlik: 0},
	{oynatxt: 0},
	{liderlik2txt: 0},
	{ses: 0},
	{mute: 0},
	{kategori: 0},
	{btnSinir: 0},
	{btnEndokrin: 0},
	{btnDuyu: 0},
	{btnDestekHar: 0},
	{btnSindirim: 0},
	{btnDolasim: 0},
	{btnSolunum: 0},
	{btnUriner: 0},
	{btnUreme: 0},
	{liderlikTablosu: 0},
	{btnA: 0},
	{btnB: 0},
	{btnC: 0},
	{btnD: 0},
	{Sprite: 0},
	{txtPuan: 0},
	{txtSoru: 0},
	{usedIndexes: 0},
	{Geri: 0},
	{AJAX: 0},
	{JSON: 0},
	{Audio: 0},
	{Mouse: 0},
	{versiyon: 0},
	{TextInput: 0},
	{gonder: 0},
	{Tablo: 0},
	{Liste: 0},
	{nick: 0},
	{puan: 0},
	{soruIndex: 0},
	{dogruCevap: 0},
	{tempIndex: 0},
	{sorubul: 0},
	{seciliKategori: 0},
	{oncekiAd: 0},
	{oncekiSkor: 0},
	{raw: 0},
	{line: 0},
	{isim: 0},
	{skor: 0}
];

self.InstanceType = {
	arkaplan: class extends self.ISpriteInstance {},
	Oyna: class extends self.ISpriteInstance {},
	liderlik: class extends self.ISpriteInstance {},
	oynatxt: class extends self.ITextInstance {},
	liderlik2txt: class extends self.ITextInstance {},
	mute: class extends self.ISpriteInstance {},
	kategori: class extends self.ITextInstance {},
	btnSinir: class extends self.IButtonInstance {},
	btnEndokrin: class extends self.IButtonInstance {},
	btnDuyu: class extends self.IButtonInstance {},
	btnDestekHar: class extends self.IButtonInstance {},
	btnSindirim: class extends self.IButtonInstance {},
	btnDolasim: class extends self.IButtonInstance {},
	btnSolunum: class extends self.IButtonInstance {},
	btnUriner: class extends self.IButtonInstance {},
	btnUreme: class extends self.IButtonInstance {},
	liderlikTablosu: class extends self.ITextInstance {},
	btnA: class extends self.IButtonInstance {},
	btnB: class extends self.IButtonInstance {},
	btnC: class extends self.IButtonInstance {},
	btnD: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	txtPuan: class extends self.ITextInstance {},
	txtSoru: class extends self.ITextInstance {},
	usedIndexes: class extends self.IArrayInstance {},
	Geri: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	versiyon: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	gonder: class extends self.IButtonInstance {},
	Tablo: class extends self.IButtonInstance {},
	Liste: class extends self.ITextInstance {}
}