const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.Button.Acts.SetSize,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Cnds.TriggerOnce
	];
};
self.C3_JsPropNameTable = [
	{kategori: 0},
	{liderlikTablosu: 0},
	{misafir: 0},
	{Tween: 0},
	{isimleGir: 0},
	{tusSinir: 0},
	{tusEndokrin: 0},
	{tusDuyuOrg: 0},
	{tusDestekHareket: 0},
	{tusSindirim: 0},
	{tusDolasim: 0},
	{tusSolunum: 0},
	{tusUriner: 0},
	{tusUreme: 0},
	{GeriTusu: 0},
	{txtSinirSist: 0},
	{txtEndokrin: 0},
	{txtDuyuORG: 0},
	{txtDestekHareket: 0},
	{txtSindirim: 0},
	{txtDolasim: 0},
	{txtSolunum: 0},
	{txtUreme: 0},
	{txtUriner: 0},
	{txtGeri: 0},
	{arrYanlisTus: 0},
	{yuzdeA: 0},
	{yuzdeB: 0},
	{yuzdeC: 0},
	{yuzdeD: 0},
	{jokerTelefontxt: 0},
	{joker50tus: 0},
	{jokerSeyirciTus: 0},
	{jokerTelefonTus: 0},
	{jokerGecTus: 0},
	{pauseBtn: 0},
	{menuArkaplan: 0},
	{pauseArka: 0},
	{tusDevam: 0},
	{anaMenuTXTPause: 0},
	{tusAnaMenuPause: 0},
	{oyunDuraklatildiTXT: 0},
	{devamTXTPause: 0},
	{arkaplanOyun: 0},
	{txtPuan: 0},
	{Pin: 0},
	{txtSoru: 0},
	{usedIndexes: 0},
	{Geri: 0},
	{soruMetni: 0},
	{tusA: 0},
	{tusB: 0},
	{tusC: 0},
	{tusD: 0},
	{tusAmetin: 0},
	{tusBmetin: 0},
	{tusCmetin: 0},
	{tusDmetin: 0},
	{soruMetni2: 0},
	{txtSure: 0},
	{txtSayisiSoru: 0},
	{tusAnaMenu: 0},
	{tusEnyuksekskor: 0},
	{mtn1: 0},
	{istatistik: 0},
	{anamenutxt: 0},
	{skorlartxt: 0},
	{arkaplan: 0},
	{liderlik: 0},
	{ses: 0},
	{mute: 0},
	{Oyna: 0},
	{liderlik2txt: 0},
	{oynatxt: 0},
	{oynatxt2: 0},
	{Oyna2Mod: 0},
	{tusA2: 0},
	{tusAmetin2: 0},
	{tusB2: 0},
	{tusBmetin2: 0},
	{tusC2: 0},
	{tusCmetin2: 0},
	{tusD2: 0},
	{tusDmetin2: 0},
	{txtSure2: 0},
	{txtPuan2: 0},
	{tusA3: 0},
	{tusAmetin3: 0},
	{tusB3: 0},
	{tusBmetin3: 0},
	{tusC3: 0},
	{tusCmetin3: 0},
	{tusD3: 0},
	{tusDmetin3: 0},
	{txtPuan3: 0},
	{txtSure3: 0},
	{joker50tus2: 0},
	{jokerGecTus2: 0},
	{jokerSeyirciTus2: 0},
	{jokerTelefonTus2: 0},
	{yanlisTuslar2: 0},
	{yuzdeA2: 0},
	{yuzdeB2: 0},
	{yuzdeC2: 0},
	{yuzdeD2: 0},
	{jokerTelefontxt2: 0},
	{AJAX: 0},
	{JSON: 0},
	{Audio: 0},
	{Mouse: 0},
	{versiyon: 0},
	{TextInput: 0},
	{gonder: 0},
	{Tablo: 0},
	{Liste: 0},
	{Touch: 0},
	{Browser: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite: 0},
	{Text4: 0},
	{Sprite2: 0},
	{ayarlar: 0},
	{AYARLARTXT: 0},
	{İSİMseç: 0},
	{çıkış: 0},
	{tuslar_oyuncu1: 0},
	{tuslar_oyuncu2: 0},
	{ekranOrani: 0},
	{nick: 0},
	{oyunModu: 0},
	{raw: 0},
	{line: 0},
	{isim: 0},
	{skor: 0},
	{puan: 0},
	{soruIndex: 0},
	{dogruCevap: 0},
	{tempIndex: 0},
	{sorubul: 0},
	{seciliKategori: 0},
	{oncekiAd: 0},
	{oncekiSkor: 0},
	{kalanSoru: 0},
	{sure: 0},
	{soruCevaplandiMi: 0},
	{dogruSayisi: 0},
	{yanlisSayisi: 0},
	{joker50Kullanildi: 0},
	{silIndex11: 0},
	{silIndex12: 0},
	{sec11: 0},
	{sec12: 0},
	{jokerSeyirciKullanildi: 0},
	{dogruYuzde: 0},
	{yanlisYuzde: 0},
	{jokerTelefonKullanildi: 0},
	{secilen: 0},
	{tahminTut: 0},
	{jokerGecKullanildi: 0},
	{oyunDuraklatildi: 0},
	{sescal: 0},
	{y1: 0},
	{y2: 0},
	{y3: 0},
	{oyuncu1_puan: 0},
	{oyuncu2_puan: 0},
	{oyuncu1_sure: 0},
	{oyuncu2_sure: 0},
	{cevaplandi1: 0},
	{cevaplandi2: 0},
	{secilen1: 0},
	{secilen2: 0},
	{oyuncu1_kontrol: 0},
	{oyuncu2_kontrol: 0},
	{kilit: 0},
	{puanKontrolKilidi: 0},
	{oyuncu1_joker50: 0},
	{oyuncu1_jokerSey: 0},
	{oyuncu1_jokerTel: 0},
	{oyuncu1_jokerGec: 0},
	{oyuncu2_jokerGec: 0},
	{oyuncu2_jokerTel: 0},
	{oyuncu2_joker50: 0},
	{oyuncu2_jokerSey: 0}
];

self.InstanceType = {
	kategori: class extends self.ITextInstance {},
	liderlikTablosu: class extends self.ITextInstance {},
	misafir: class extends self.ITextInstance {},
	isimleGir: class extends self.ITextInstance {},
	tusSinir: class extends self.IWorldInstance {},
	tusEndokrin: class extends self.IWorldInstance {},
	tusDuyuOrg: class extends self.IWorldInstance {},
	tusDestekHareket: class extends self.IWorldInstance {},
	tusSindirim: class extends self.IWorldInstance {},
	tusDolasim: class extends self.IWorldInstance {},
	tusSolunum: class extends self.IWorldInstance {},
	tusUriner: class extends self.IWorldInstance {},
	tusUreme: class extends self.IWorldInstance {},
	GeriTusu: class extends self.IWorldInstance {},
	txtSinirSist: class extends self.ITextInstance {},
	txtEndokrin: class extends self.ITextInstance {},
	txtDuyuORG: class extends self.ITextInstance {},
	txtDestekHareket: class extends self.ITextInstance {},
	txtSindirim: class extends self.ITextInstance {},
	txtDolasim: class extends self.ITextInstance {},
	txtSolunum: class extends self.ITextInstance {},
	txtUreme: class extends self.ITextInstance {},
	txtUriner: class extends self.ITextInstance {},
	txtGeri: class extends self.ITextInstance {},
	arrYanlisTus: class extends self.IArrayInstance {},
	yuzdeA: class extends self.ITextInstance {},
	yuzdeB: class extends self.ITextInstance {},
	yuzdeC: class extends self.ITextInstance {},
	yuzdeD: class extends self.ITextInstance {},
	jokerTelefontxt: class extends self.ITextInstance {},
	joker50tus: class extends self.ISpriteInstance {},
	jokerSeyirciTus: class extends self.ISpriteInstance {},
	jokerTelefonTus: class extends self.ISpriteInstance {},
	jokerGecTus: class extends self.ISpriteInstance {},
	pauseBtn: class extends self.ISpriteInstance {},
	menuArkaplan: class extends self.IWorldInstance {},
	pauseArka: class extends self.ISpriteInstance {},
	tusDevam: class extends self.IWorldInstance {},
	anaMenuTXTPause: class extends self.ITextInstance {},
	tusAnaMenuPause: class extends self.IWorldInstance {},
	oyunDuraklatildiTXT: class extends self.ITextInstance {},
	devamTXTPause: class extends self.ITextInstance {},
	arkaplanOyun: class extends self.ISpriteInstance {},
	txtPuan: class extends self.ITextInstance {},
	txtSoru: class extends self.ITextInstance {},
	usedIndexes: class extends self.IArrayInstance {},
	Geri: class extends self.IButtonInstance {},
	soruMetni: class extends self.ISpriteInstance {},
	tusA: class extends self.ISpriteInstance {},
	tusB: class extends self.ISpriteInstance {},
	tusC: class extends self.ISpriteInstance {},
	tusD: class extends self.ISpriteInstance {},
	tusAmetin: class extends self.ITextInstance {},
	tusBmetin: class extends self.ITextInstance {},
	tusCmetin: class extends self.ITextInstance {},
	tusDmetin: class extends self.ITextInstance {},
	soruMetni2: class extends self.IWorldInstance {},
	txtSure: class extends self.ITextInstance {},
	txtSayisiSoru: class extends self.ITextInstance {},
	tusAnaMenu: class extends self.IWorldInstance {},
	tusEnyuksekskor: class extends self.IWorldInstance {},
	mtn1: class extends self.ITextInstance {},
	istatistik: class extends self.ITextInstance {},
	anamenutxt: class extends self.ITextInstance {},
	skorlartxt: class extends self.ITextInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	liderlik: class extends self.ISpriteInstance {},
	mute: class extends self.ISpriteInstance {},
	Oyna: class extends self.ISpriteInstance {},
	liderlik2txt: class extends self.ITextInstance {},
	oynatxt: class extends self.ITextInstance {},
	oynatxt2: class extends self.ITextInstance {},
	Oyna2Mod: class extends self.IWorldInstance {},
	tusA2: class extends self.ISpriteInstance {},
	tusAmetin2: class extends self.ITextInstance {},
	tusB2: class extends self.ISpriteInstance {},
	tusBmetin2: class extends self.ITextInstance {},
	tusC2: class extends self.ISpriteInstance {},
	tusCmetin2: class extends self.ITextInstance {},
	tusD2: class extends self.ISpriteInstance {},
	tusDmetin2: class extends self.ITextInstance {},
	txtSure2: class extends self.ITextInstance {},
	txtPuan2: class extends self.ITextInstance {},
	tusA3: class extends self.ISpriteInstance {},
	tusAmetin3: class extends self.ITextInstance {},
	tusB3: class extends self.ISpriteInstance {},
	tusBmetin3: class extends self.ITextInstance {},
	tusC3: class extends self.ISpriteInstance {},
	tusCmetin3: class extends self.ITextInstance {},
	tusD3: class extends self.ISpriteInstance {},
	tusDmetin3: class extends self.ITextInstance {},
	txtPuan3: class extends self.ITextInstance {},
	txtSure3: class extends self.ITextInstance {},
	joker50tus2: class extends self.ISpriteInstance {},
	jokerGecTus2: class extends self.ISpriteInstance {},
	jokerSeyirciTus2: class extends self.ISpriteInstance {},
	jokerTelefonTus2: class extends self.ISpriteInstance {},
	yanlisTuslar2: class extends self.IArrayInstance {},
	yuzdeA2: class extends self.ITextInstance {},
	yuzdeB2: class extends self.ITextInstance {},
	yuzdeC2: class extends self.ITextInstance {},
	yuzdeD2: class extends self.ITextInstance {},
	jokerTelefontxt2: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	versiyon: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	gonder: class extends self.IButtonInstance {},
	Tablo: class extends self.IButtonInstance {},
	Liste: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ayarlar: class extends self.ISpriteInstance {},
	AYARLARTXT: class extends self.ITextInstance {},
	İSİMseç: class extends self.ITextInstance {},
	çıkış: class extends self.ITextInstance {},
	tuslar_oyuncu1: class extends self.ISpriteInstance {},
	tuslar_oyuncu2: class extends self.ISpriteInstance {}
}